#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * eqrayphp CLI 入口文件
 *
 * @package eqrayphp
 * @author  eqrayphp Team
 */

// ✅ 修复：定义项目根目录常量（必须添加这行）
define('BASE_PATH', __DIR__);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Framework\Container\Container;
use Framework\Core\App;
// 原有命令
use Framework\Console\Commands\MakeControllerCommand;
use Framework\Console\Commands\MakeModelCommand;
use Framework\Console\Commands\MakeMiddlewareCommand;
use Framework\Console\Commands\MakeEventCommand;
use Framework\Console\Commands\MakeListenerCommand;
// 路由命令
use Framework\Console\Commands\RouteListCommand;

// 初始化容器，确保 CLI 命令中可使用 app() / App::make()
Container::init();
App::setContainer(Container::getInstance());


$application = new Application('Novaphp Framework', '0.8.1');

// ============ 注册命令 ============
// Symfony Console 7.3 起 add() 更名为 addCommand()，此处做兼容判断
$commands = [
    new MakeControllerCommand(),
    new MakeModelCommand(),
    new MakeMiddlewareCommand(),
    new MakeEventCommand(),
    new MakeListenerCommand(),
    new RouteListCommand(),
];
foreach ($commands as $cmd) {
    method_exists($application, 'addCommand')
        ? $application->addCommand($cmd)
        : $application->add($cmd);
}

$application->run();

# ============ 可用命令列表 ============
#
# 生成控制器：
#   php novaphp make:controller User
#
# 生成模型：
#   php novaphp make:model User
#
# 生成中间件：
#   php novaphp make:middleware Auth
#
# 生成事件：
#   php novaphp make:event UserRegistered
#
# 生成监听器：
#   php novaphp make:listener UserNotification
#
# 路由查看：
#   php novaphp route:list
#   php novaphp route:list --method=GET
#   php novaphp route:list --path=/api